Parsable object layers
SavagePastaMan/pyweek-2021 pull request #30
Opened 2021-03-30 20:30 UTC by ForbiddenKJ

all objects when being parsed are sorted into their types and returned in a dictionary by these sorted types. Our return will be in the format of this `dict[str, list[ObjectLayer]]` and will look like this `{"guard": [], "key": []}`. We don't really care about the order of the elements in the array, this is fine although the types are relevant.

2021-03-30 20:47 UTC, GDWR approved these changes
Looks good, would be better if we could have a more abstract method to allow for other object layers in the future. But time constraints are a thing.

2021-03-30 23:46 UTC, SavagePastaMan requested changes
looks good other than my one comment

2021-03-30 23:46 UTC, SavagePastaMan commented on __main__.py
> +        ]
Both these loops can be done more pythonically
```suggestion
        self.guard_locations = [
            utils.extract_locations(guard)
            for guard in self.object_layers["guard"])
        ]
```
not sure if guard is the best name, but something like this

2021-03-30 23:47 UTC, SavagePastaMan commented
watch out for merge conflicts in `constants.py`

2021-03-31 21:26 UTC, SavagePastaMan approved these changes

2021-03-31 21:27 UTC, merged